Codebreaker-web app
DaniilYusha/codebreaker-web pull request #1
Opened 2020-08-20 14:11 UTC by DaniilYusha

2020-08-21 14:25 UTC, Mikkko reviewed
seems good

2020-08-21 14:25 UTC, Mikkko commented on config.ru
> +use Rack::Reloader
remove in production please

2020-08-21 14:25 UTC, Mikkko commented on Gemfile
> +  gem 'rack_session_access', '~> 0.2.0'
i think you can remove it

2020-08-21 14:25 UTC, Mikkko commented on spec/spec_helper.rb
> +require 'rack_session_access/capybara'
i think you can remove this

2020-08-21 16:14 UTC, DaniilYusha commented on Gemfile
> +  gem 'rack_session_access', '~> 0.2.0'
@Mikkko I can't because I use session thanks to this gem

2020-08-21 16:44 UTC, exposwingie commented on .gitignore
> +app/db/game.yml
add empty line pls

2020-08-21 16:44 UTC, exposwingie commented on .rubocop.yml
> +    - 'spec/**/*.rb'
empty line

2020-08-21 16:44 UTC, exposwingie commented on config.ru
> +use Rack::Reloader
off in production pls

2020-08-21 16:44 UTC, exposwingie commented on views/game.html.erb
> +                  <span class="badge badge-light"><%= game.difficulty.current_hints %></span>
Please disable hints button and 'Hints: ' when hints is out

2020-08-21 16:44 UTC, exposwingie commented on spec/spec_helper.rb
> +require 'rack'
move rack to autoload

2020-08-21 21:20 UTC, DaniilYusha commented on config.ru
> +use Rack::Reloader
Done

2020-08-21 21:20 UTC, DaniilYusha commented on spec/spec_helper.rb
> +require 'rack_session_access/capybara'
Can't remove because I use it now

2020-08-21 21:22 UTC, DaniilYusha commented on .gitignore
> +app/db/game.yml
Done

2020-08-21 21:22 UTC, DaniilYusha commented on .rubocop.yml
> +    - 'spec/**/*.rb'
Done

2020-08-21 21:23 UTC, DaniilYusha commented on config.ru
> +use Rack::Reloader
Done

2020-08-21 21:23 UTC, DaniilYusha commented on spec/spec_helper.rb
> +require 'rack'
Done

2020-08-21 21:26 UTC, DaniilYusha commented on views/game.html.erb
> +                  <span class="badge badge-light"><%= game.difficulty.current_hints %></span>
@exposwingie I have it below :smile:

2020-08-21 22:33 UTC, exposwingie commented on views/game.html.erb
> +                  <span class="badge badge-light"><%= game.difficulty.current_hints %></span>
no, do it disabled = true

2020-08-21 22:44 UTC, Mikkko requested changes
seems good

2020-08-21 22:44 UTC, Mikkko commented on app/codebreaker_web/helpers/data_management_helper.rb
> +      @request.params[param]
please remove instance variables from module

2020-08-21 22:44 UTC, Mikkko commented on app/codebreaker_web/helpers/data_management_helper.rb
> +      @request.session.clear
as above

2020-08-21 22:44 UTC, Mikkko commented on app/codebreaker_web/helpers/data_management_helper.rb
> +      @request.session[param]
as above

2020-08-21 22:44 UTC, Mikkko commented on spec/codebreaker_web/web_application_spec.rb
> +      page.set_rack_session(game_path: TEST_GAME_FILE)
You write it a lot of times. Maybe better to create top level context with 1 before for this? After, you could remove this repeated lines.

2020-08-21 22:44 UTC, Mikkko commented on spec/codebreaker_web/web_application_spec.rb
> +    after { File.delete TEST_GAME_PATH }
as above. you could write 1 after and don't repeat this

2020-08-21 22:52 UTC, exposwingie commented on views/menu.html.erb
> +                  <option value="hell"><%= I18n.t('levels.hell') %></option>
please do as written in the requirements difficulty - attempts amount - hints amount

2020-08-21 22:52 UTC, exposwingie commented on views/statistics.html.erb
> +                      <td><%= user[:date] %></td>
please do as written in the requirements without +0000

2020-08-21 22:52 UTC, exposwingie commented on app/codebreaker_web/web_application.rb
> +    end
you can move it to private to

2020-08-21 22:56 UTC, DaniilYusha commented on views/game.html.erb
> +                  <span class="badge badge-light"><%= game.difficulty.current_hints %></span>
@exposwingie ok, understand and done, thanks

2020-08-21 22:58 UTC, DaniilYusha commented on app/codebreaker_web/web_application.rb
> +    end
done

2020-08-21 23:22 UTC, DaniilYusha commented on views/statistics.html.erb
> +                      <td><%= user[:date] %></td>
Done

2020-08-22 09:49 UTC, DaniilYusha commented on views/menu.html.erb
> +                  <option value="hell"><%= I18n.t('levels.hell') %></option>
Done

2020-08-22 09:53 UTC, DaniilYusha commented on app/codebreaker_web/helpers/data_management_helper.rb
> +      @request.params[param]
done

2020-08-22 09:53 UTC, DaniilYusha commented on app/codebreaker_web/helpers/data_management_helper.rb
> +      @request.session.clear
done

2020-08-22 09:53 UTC, DaniilYusha commented on app/codebreaker_web/helpers/data_management_helper.rb
> +      @request.session[param]
done

2020-08-22 10:11 UTC, DaniilYusha commented on spec/codebreaker_web/web_application_spec.rb
> +      page.set_rack_session(game_path: TEST_GAME_FILE)
done

2020-08-22 10:11 UTC, DaniilYusha commented on spec/codebreaker_web/web_application_spec.rb
> +    after { File.delete TEST_GAME_PATH }
done

2020-08-23 08:39 UTC, Mikkko approved these changes
seems good

2020-08-23 16:24 UTC, exposwingie approved these changes

2020-08-25 11:15 UTC, epoberezhny requested changes

2020-08-25 11:15 UTC, epoberezhny commented on app/codebreaker_web/helpers/data_management_helper.rb
> +  module DataManagementHelper
Looks more like response helpers

2020-08-25 11:15 UTC, epoberezhny commented on app/codebreaker_web/helpers/game_storage_helper.rb
> +      "game_#{8.times.map { rand(10) }.join}.yml"
FYI you could use `SecureRandom.uuid`

2020-08-25 11:15 UTC, epoberezhny commented on app/codebreaker_web/web_application.rb
> +    attr_reader :statistics
Why do we need it?

2020-08-25 11:15 UTC, epoberezhny commented on config.ru
> +use RackSessionAccess::Middleware if ENV.fetch('RACK_ENV', 'development') == 'development'
Maybe it would be better to use the same condition as in the autoload?

2020-08-25 11:15 UTC, epoberezhny commented on spec/codebreaker_web/web_application_spec.rb
> +      game.difficulty.instance_variable_set(:@current_attempts, 1)
Try to avoid using of `instance_variable_set` outside of class in the future

2020-08-25 11:24 UTC, epoberezhny commented
Add focus for the input. It will improve user experience

2020-08-25 11:34 UTC, DaniilYusha commented on app/codebreaker_web/helpers/game_storage_helper.rb
> +      "game_#{8.times.map { rand(10) }.join}.yml"
done

2020-08-25 11:34 UTC, DaniilYusha commented on config.ru
> +use RackSessionAccess::Middleware if ENV.fetch('RACK_ENV', 'development') == 'development'
ok, done, thanks

2020-08-25 11:43 UTC, DaniilYusha commented on app/codebreaker_web/helpers/data_management_helper.rb
> +  module DataManagementHelper
renamed, thx :rocket:

2020-08-25 11:47 UTC, DaniilYusha commented on app/codebreaker_web/web_application.rb
> +    attr_reader :statistics
Removed that, thanks

2020-08-25 11:56 UTC, epoberezhny approved these changes

2021-02-09 15:00 UTC, merged